from cryptography.fernet import Fernet
key = Fernet.generate_key() # GERA UMA CHAVE RANDÔMICA, COM BASE 64
file = open('./keys/chave.key', 'wb')
file.write(key)
file.close()
print()
print("A CHAVE ABERTA É: ")
print(key)
print()
file = open('./keys/chave.key', 'rb')
chave_lida = file.read()
file.close()
print()
print("A CHAVE LIDA É: ")
print(chave_lida)
print()